version: 2

multi-ecosystem-groups:
  web:
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  backend:
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    patterns: ["*"]
    multi-ecosystem-group: "web"

  - package-ecosystem: "npm"
    directory: "/electron"
    patterns: ["*"]
    multi-ecosystem-group: "web"

  - package-ecosystem: "gomod"
    directory: "/backend"
    patterns: ["*"]
    multi-ecosystem-group: "backend"
