version: 2

multi-ecosystem-groups:
  web:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    patterns: ["*"]
    multi-ecosystem-group: "web"

  - package-ecosystem: "npm"
    directory: "/electron"
    patterns: ["*"]
    multi-ecosystem-group: "web"

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"