/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppOverlays: typeof import('./src/components/layout/AppOverlays.vue')['default']
    AudioControls: typeof import('./src/components/AudioControls.vue')['default']
    AudioDeafenButton: typeof import('./src/components/AudioDeafenButton.vue')['default']
    AudioStream: typeof import('./src/components/AudioStream.vue')['default']
    AudioTab: typeof import('./src/components/debug/AudioTab.vue')['default']
    CategoryModal: typeof import('./src/components/CategoryModal.vue')['default']
    ConfirmDeleteCategoryModal: typeof import('./src/components/ConfirmDeleteCategoryModal.vue')['default']
    ConfirmDeleteRoomModal: typeof import('./src/components/ConfirmDeleteRoomModal.vue')['default']
    ConnectionIssuesCard: typeof import('./src/components/debug/ConnectionIssuesCard.vue')['default']
    DebugDashboard: typeof import('./src/components/DebugDashboard.vue')['default']
    DebugHeader: typeof import('./src/components/debug/DebugHeader.vue')['default']
    DebugToggle: typeof import('./src/components/debug/DebugToggle.vue')['default']
    DesktopSidebar: typeof import('./src/components/layout/DesktopSidebar.vue')['default']
    EditRoomModal: typeof import('./src/components/EditRoomModal.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    IceCandidateCard: typeof import('./src/components/debug/IceCandidateCard.vue')['default']
    IceCandidatesTab: typeof import('./src/components/debug/IceCandidatesTab.vue')['default']
    IssuesTab: typeof import('./src/components/debug/IssuesTab.vue')['default']
    LogsTab: typeof import('./src/components/debug/LogsTab.vue')['default']
    MainContent: typeof import('./src/components/layout/MainContent.vue')['default']
    MetricsCard: typeof import('./src/components/debug/MetricsCard.vue')['default']
    MetricsTab: typeof import('./src/components/debug/MetricsTab.vue')['default']
    MicMuteButton: typeof import('./src/components/MicMuteButton.vue')['default']
    MobileRoomView: typeof import('./src/components/layout/MobileRoomView.vue')['default']
    ModalManager: typeof import('./src/components/ModalManager.vue')['default']
    NetworkPathCard: typeof import('./src/components/debug/NetworkPathCard.vue')['default']
    NetworkTab: typeof import('./src/components/debug/NetworkTab.vue')['default']
    RoomCard: typeof import('./src/components/RoomCard.vue')['default']
    RoomHeader: typeof import('./src/components/RoomHeader.vue')['default']
    RoomModal: typeof import('./src/components/RoomModal.vue')['default']
    RoomSidebar: typeof import('./src/components/RoomSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenShareArea: typeof import('./src/components/ScreenShareArea.vue')['default']
    ScreenShareButton: typeof import('./src/components/ScreenShareButton.vue')['default']
    ScreenShareDebugCard: typeof import('./src/components/debug/ScreenShareDebugCard.vue')['default']
    ScreenShareQualityModal: typeof import('./src/components/ScreenShareQualityModal.vue')['default']
    ScreenShareTab: typeof import('./src/components/debug/ScreenShareTab.vue')['default']
    ScreenStream: typeof import('./src/components/ScreenStream.vue')['default']
    ThumbnailStream: typeof import('./src/components/ThumbnailStream.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    UserControlPanel: typeof import('./src/components/UserControlPanel.vue')['default']
    UserGrid: typeof import('./src/components/UserGrid.vue')['default']
    UserSidebar: typeof import('./src/components/UserSidebar.vue')['default']
    UserSidebarWrapper: typeof import('./src/components/layout/UserSidebarWrapper.vue')['default']
  }
}
