services:
  frontend:
    image: orbital-frontend:${VERSION}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - orbital-network

  backend:
    image: orbital-backend:${VERSION}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GIN_MODE=release
      - PORT=8080
      - TURN_URL=${TURN_URL:-turn:localhost:3478}
      - TURN_TLS_URL=${TURN_TLS_URL:-turns:localhost:5349}
      - STUN_URLS=${STUN_URLS:-stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302}
    depends_on:
      - turn-server
    networks:
      - orbital-network

  turn-server:
    image: coturn/coturn:4.8.0
    container_name: orb-coturn
    restart: unless-stopped
    # For performance reason use host network
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./configs/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./data/turn:/var/lib/coturn
    command: >
      sh -c "
        turnserver
        -c /etc/coturn/turnserver.conf
        --use-auth-secret
        --static-auth-secret=$${TURN_SECRET}
      "

networks:
  orbital-network:
    driver: bridge
