export * from "./client"

import {
  getRooms,
  getRoom,
  createRoom,
  updateRoom,
  deleteRoom,
  joinRoom,
  leaveRoom,
  kickUser,
  getRoomUsers,
  updateRoomOrder,
  getLiveKitToken,
  getTurnConfig,
} from "./rooms"

import {
  getOAuthUrl,
  initiateOAuthLogin,
  initiateDiscordLogin,
  initiateGoogleLogin,
  guestLogin,
  register,
  loginPassword,
  logout,
  getCurrentUser,
  getAuthStatus,
} from "./auth"

import {
  getCategories,
  createCategory,
  renameCategory,
  deleteCategory,
  updateCategoryOrder,
} from "./categories"

import {
  getUsers,
  getUserRole,
  promoteUser,
  demoteUser,
  deleteUser,
  deleteAllGuests,
  getAllUsers,
  sendLogs,
  getLogs,
  getLog,
  deleteLog,
  getAudioFiles,
  uploadAudio,
  deleteAudio,
  renameAudio,
  getAudioUrl,
  enableRoomStats,
  disableRoomStats,
  subscribeRoomStats,
  unsubscribeRoomStats,
  getStatsStatus,
  healthCheck,
} from "./admin"

import { uploadAvatar, updateSoundPack, getConfig } from "./user"

export const apiService = {
  getRooms,
  getRoom,
  createRoom,
  updateRoom,
  deleteRoom,
  joinRoom,
  leaveRoom,
  kickUser,
  getRoomUsers,
  updateRoomOrder,
  getLiveKitToken,
  getTurnConfig,

  getOAuthUrl,
  initiateOAuthLogin,
  initiateDiscordLogin,
  initiateGoogleLogin,
  guestLogin,
  register,
  loginPassword,
  logout,
  getCurrentUser,
  getAuthStatus,

  getCategories,
  createCategory,
  renameCategory,
  deleteCategory,
  updateCategoryOrder,

  getUsers,
  getUserRole,
  promoteUser,
  demoteUser,
  deleteUser,
  deleteAllGuests,
  getAllUsers,
  sendLogs,
  getLogs,
  getLog,
  deleteLog,
  getAudioFiles,
  uploadAudio,
  deleteAudio,
  renameAudio,
  getAudioUrl,
  enableRoomStats,
  disableRoomStats,
  subscribeRoomStats,
  unsubscribeRoomStats,
  getStatsStatus,
  healthCheck,

  uploadAvatar,
  updateSoundPack,
  getConfig,
}
